const quizDeck = [
  { question: "Who built the ark?", options: ["Moses", "Noah", "David", "Paul"], answer: "Noah" },
  { question: "Which book comes first in the Bible?", options: ["Genesis", "John", "Romans", "Psalms"], answer: "Genesis" },
  { question: "Who defeated Goliath?", options: ["Samuel", "David", "Peter", "Joshua"], answer: "David" },
  { question: "Who led Israel out of Egypt?", options: ["Moses", "Elijah", "Isaiah", "Job"], answer: "Moses" },
  { question: "Where was Jesus born?", options: ["Nazareth", "Bethlehem", "Jerusalem", "Capernaum"], answer: "Bethlehem" },
  { question: "Who was swallowed by a great fish?", options: ["Jonah", "Micah", "Paul", "Andrew"], answer: "Jonah" },
  { question: "Who baptized Jesus?", options: ["Peter", "John the Baptist", "James", "Philip"], answer: "John the Baptist" },
  { question: "How many disciples did Jesus choose?", options: ["10", "11", "12", "13"], answer: "12" },
  { question: "Who denied Jesus three times?", options: ["Peter", "John", "Thomas", "Matthew"], answer: "Peter" },
  { question: "What is the last book of the Bible?", options: ["Jude", "Revelation", "Romans", "Acts"], answer: "Revelation" },
  { question: "Who was known for great wisdom as king?", options: ["Saul", "David", "Solomon", "Hezekiah"], answer: "Solomon" },
  { question: "What did Jesus turn water into?", options: ["Juice", "Wine", "Oil", "Milk"], answer: "Wine" },
  { question: "Who climbed a tree to see Jesus?", options: ["Nicodemus", "Zacchaeus", "Bartimaeus", "Lazarus"], answer: "Zacchaeus" },
  { question: "Who walked on water with Jesus?", options: ["Peter", "Andrew", "James", "Philip"], answer: "Peter" },
  { question: "Who was thrown into a den of lions?", options: ["Daniel", "Jeremiah", "Ezekiel", "Hosea"], answer: "Daniel" },
  { question: "Which city walls fell after trumpet blasts?", options: ["Nineveh", "Jericho", "Babylon", "Tyre"], answer: "Jericho" },
  { question: "Who interpreted Pharaoh's dreams?", options: ["Moses", "Joseph", "Aaron", "Nehemiah"], answer: "Joseph" },
  { question: "Who was Abraham's wife?", options: ["Rachel", "Leah", "Sarah", "Rebekah"], answer: "Sarah" },
  { question: "Who was Isaac's son?", options: ["Jacob", "Eli", "Samuel", "Saul"], answer: "Jacob" },
  { question: "What is the shortest verse in many English Bibles?", options: ["Pray always", "God is love", "Jesus wept", "Be still"], answer: "Jesus wept" },
  { question: "Who wrote many Psalms?", options: ["David", "Paul", "Luke", "Ezra"], answer: "David" },
  { question: "Who rebuilt Jerusalem's walls?", options: ["Nehemiah", "Elijah", "Amos", "Joel"], answer: "Nehemiah" },
  { question: "Who was Esther's cousin and guardian?", options: ["Mordecai", "Haman", "Cyrus", "Ezra"], answer: "Mordecai" },
  { question: "Who was thrown into a fiery furnace with two others?", options: ["Daniel", "Shadrach", "Isaiah", "Samuel"], answer: "Shadrach" },
  { question: "Who replaced Judas among the apostles?", options: ["Matthias", "Barnabas", "Silas", "Timothy"], answer: "Matthias" },
  { question: "Who wrote the book of Acts?", options: ["Luke", "Mark", "John", "Peter"], answer: "Luke" },
  { question: "Who said, 'Here I am, send me'?", options: ["Jeremiah", "Isaiah", "Ezekiel", "Habakkuk"], answer: "Isaiah" },
  { question: "What fruit did the spies bring from Canaan?", options: ["Dates", "Pomegranates", "Grapes", "Figs"], answer: "Grapes" },
  { question: "Who was the first king of Israel?", options: ["David", "Saul", "Solomon", "Samuel"], answer: "Saul" },
  { question: "What was Paul's name before conversion?", options: ["Silas", "Saul", "Simeon", "Stephen"], answer: "Saul" },
  { question: "Who fell asleep and fell from a window while Paul preached?", options: ["Tychicus", "Eutychus", "Onesimus", "Apollos"], answer: "Eutychus" },
  { question: "Who was Jesus' mother?", options: ["Martha", "Mary", "Elizabeth", "Anna"], answer: "Mary" },
  { question: "Who announced Jesus' birth to Mary?", options: ["Michael", "Gabriel", "Raphael", "Uriel"], answer: "Gabriel" },
  { question: "Who was the strongest judge in Israel?", options: ["Gideon", "Samson", "Jephthah", "Ehud"], answer: "Samson" },
  { question: "What did God give Moses on Mount Sinai?", options: ["A crown", "Ten Commandments", "Ark plans", "A scroll"], answer: "Ten Commandments" },
  { question: "Who asked for wisdom from God?", options: ["Solomon", "Saul", "Absalom", "Rehoboam"], answer: "Solomon" },
  { question: "Who fed Elijah during famine?", options: ["A raven", "A dove", "An eagle", "A lamb"], answer: "A raven" },
  { question: "Who was known as the weeping prophet?", options: ["Isaiah", "Jeremiah", "Ezekiel", "Daniel"], answer: "Jeremiah" },
  { question: "Which apostle was a tax collector?", options: ["Matthew", "John", "Thomas", "Philip"], answer: "Matthew" },
  { question: "Who touched Jesus' cloak and was healed?", options: ["Widow of Nain", "Woman with bleeding", "Mary Magdalene", "Lydia"], answer: "Woman with bleeding" },
  { question: "Who was Jesus' earthly father?", options: ["Zechariah", "Joseph", "Simeon", "Joachim"], answer: "Joseph" },
  { question: "Who dreamed of a ladder to heaven?", options: ["Isaac", "Jacob", "Joseph", "Moses"], answer: "Jacob" },
  { question: "How many days did Jesus fast in the wilderness?", options: ["7", "21", "30", "40"], answer: "40" },
  { question: "Who saw a burning bush?", options: ["Moses", "Aaron", "Joshua", "Caleb"], answer: "Moses" },
  { question: "Who was thrown overboard during a storm?", options: ["Jonah", "Nahum", "Obadiah", "Amos"], answer: "Jonah" },
  { question: "What did Jesus ride into Jerusalem?", options: ["Horse", "Camel", "Donkey", "Chariot"], answer: "Donkey" },
  { question: "Who helped carry Jesus' cross?", options: ["Joseph of Arimathea", "Simon of Cyrene", "Nicodemus", "Pilate"], answer: "Simon of Cyrene" },
  { question: "Who was the first martyr in Acts?", options: ["James", "Stephen", "Philip", "Barnabas"], answer: "Stephen" },
  { question: "Who was Paul's missionary partner on first journey?", options: ["Barnabas", "Luke", "Timothy", "Titus"], answer: "Barnabas" },
  { question: "Who interpreted writing on the wall for Belshazzar?", options: ["Ezekiel", "Daniel", "Nehemiah", "Ezra"], answer: "Daniel" },
  { question: "Which sea did Jesus calm during a storm?", options: ["Dead Sea", "Red Sea", "Sea of Galilee", "Mediterranean"], answer: "Sea of Galilee" },
  { question: "Who said, 'As for me and my house, we will serve the Lord'?", options: ["Joshua", "Caleb", "Moses", "Aaron"], answer: "Joshua" },
  { question: "What city was Paul traveling to when Jesus met him?", options: ["Rome", "Jerusalem", "Damascus", "Athens"], answer: "Damascus" }
];

export default quizDeck;
